version: '3.8'

services:
  app:
    build: 
      context: .
      # dockerfile: Dockerfile
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app
